In [19]:
import pandas as pd
import glob


data_folder = "data/hash_additive_manufacturing"

csv_files = glob.glob(f"{data_folder}/*.csv")

combined_df = pd.concat((pd.read_csv(file) for file in csv_files), ignore_index=True)
combined_df['Date'] = pd.to_datetime(combined_df['Date'])
combined_df

,Author Name,Author ID,Date,Post Text,Replies,Likes,Reshares,Views
0,Paanduv Applications,@PaanduvA,2024-12-06 05:56:56+00:00,I Tried Simulating 20 layers of Maraging Steel...,0,0,1,2125
1,Liza Lepczyk Allison-CMU NextManufacturing Center,@LizaAllisonCMU,2024-11-15 12:50:38+00:00,Grateful to be a part of an excellent event la...,0,0,0,0
2,DSIAC,@DSIAC,2024-10-21 19:45:01+00:00,𝟰𝟴𝘁𝗵 𝗙𝗶𝗴𝗵𝘁𝗲𝗿 𝗪𝗶𝗻𝗴 𝗔𝗶𝗿𝗺𝗲𝗻 𝗖𝗿𝗲𝗮𝘁𝗲 𝗡𝗲𝘄 𝗧𝗲𝗰𝗵𝗻𝗼𝗹𝗼𝗴𝘆...,0,0,0,0
3,3D Print .com,@3DPrintBoard,2024-12-18 18:47:28+00:00,"Have you read ""Always In Stock"" yet? This free...",0,0,0,0
4,3Printr.com,@3printr,2024-07-02 11:54:08+00:00,Penn State University develops 3D printable ma...,0,0,0,62
...,...,...,...,...,...,...,...,...
4030,3D Printing News,@My3DPrinting,2024-12-18 18:47:16+00:00,"Have you read ""Always In Stock"" yet? This free...",0,0,0,0
4031,Nexa3D,@Nexa3D,2024-07-03 15:58:20+00:00,Learn how Nexa3D is revolutionizing semiconduc...,0,2,1,70
4032,3D-grenzenlos Magazin,@3Dgrenzenlos,2024-06-26 08:08:43+00:00,Nikon SLM Solutions startet die Produktion des...,0,0,0,42
4033,NNI,@NNInanonews,2024-06-21 20:36:47+00:00,Interested in #nanotechnology and #Additive...,0,0,0,0
4034,SME Education Foundation,@mfgeducation,2024-04-19 13:00:10+00:00,We loved watching the 2024 FIRST ( @FIRSTweets...,0,0,0,0

In [22]:
# Find duplicate rows based on 'Date' and 'Author ID'
duplicate_rows = combined_df[combined_df.duplicated(subset=['Date', 'Author ID'], keep=False)]
duplicate_rows.sort_values(by=['Date', 'Author ID'])

,Author Name,Author ID,Date,Post Text,Replies,Likes,Reshares,Views
2659,3D Systems,@3dsystems,2023-07-27 14:02:33+00:00,Unknown Post Content,0,16,12,790
3360,3D Systems,@3dsystems,2023-07-27 14:02:33+00:00,Unknown Post Content,0,16,12,790
805,Geometric Solutions,@GeomSolutions,2024-04-02 15:00:36+00:00,Facing delays with small machined #Parts ? Le...,0,0,0,0
3789,Geometric Solutions,@GeomSolutions,2024-04-02 15:00:36+00:00,Facing delays with small machined #Parts ? Le...,0,0,0,0
735,3Printr.com,@3printr,2024-04-03 12:37:36+00:00,FANTASEA: Ocean depths as a source of inspirat...,0,0,0,110
...,...,...,...,...,...,...,...,...
3008,Vision Miner,@VisionMiner,2024-12-27 17:52:16+00:00,#3dprinting will change the way you think abo...,0,0,0,43
3522,Vision Miner,@VisionMiner,2024-12-27 17:52:16+00:00,#3dprinting will change the way you think abo...,0,0,0,43
2042,Trinus Corporation,@TrinusOfficial,2024-12-27 19:55:03+00:00,Find out the top 10 #ManufacturingTrends & ...,0,0,0,0
2768,Trinus Corporation,@TrinusOfficial,2024-12-27 19:55:03+00:00,Find out the top 10 #ManufacturingTrends & ...,0,0,0,0
3405,Trinus Corporation,@TrinusOfficial,2024-12-27 19:55:03+00:00,Find out the top 10 #ManufacturingTrends & ...,0,0,0,0

In [21]:
unique_rows = combined_df.drop_duplicates(subset=['Date', 'Author ID'])

# Get the count of unique rows
unique_count = unique_rows.shape[0]

print(f"Number of unique rows based on 'Date' and 'Author ID': {unique_count}")

Number of unique rows based on 'Date' and 'Author ID': 1447

In [ ]:

combined_df['Date'] = pd.to_datetime(combined_df['Date'])

unique_rows = combined_df.drop_duplicates(subset=['Date', 'Author ID'])

unique_rows['Month'] = unique_rows['Date'].dt.to_period('M')

post_count_by_month = unique_rows.groupby('Month')['Post Text'].count()

print(post_count_by_month)

Month
2023-07      1
2024-03     67
2024-04     66
2024-05     88
2024-06     72
2024-07    112
2024-08    104
2024-09    123
2024-10    257
2024-11    347
2024-12    210
Freq: M, Name: Post Text, dtype: int64

/tmp/ipykernel_22103/1716499280.py:8: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  unique_rows['Month'] = unique_rows['Date'].dt.to_period('M')
/tmp/ipykernel_22103/1716499280.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  unique_rows['Month'] = unique_rows['Date'].dt.to_period('M')

# Tweets Collection By Date

In [ ]:
import pandas as pd
import glob

#data_folder = "data/keyphrase_search_results_raw/by_date/01_2024"
data_folder = "data/keyphrase_search_results_raw/by_date"

csv_files = glob.glob(f"{data_folder}/**/*.csv", recursive=True)

df = pd.concat((pd.read_csv(file) for file in csv_files), ignore_index=True)

df['Date'] = pd.to_datetime(df['Date'])
df

,Author Name,Author ID,Date,Post Text,Replies,Likes,Reshares,Views
0,Al Mishek,@AlMishek,2023-12-27 16:19:47+00:00,Enjoyed my Cranberry Old Fashion with my newly...,0,0,0,0
1,☾༺ℓυa༻☽cazavampitos// ENCARGOS 3D OPEN,@Puchiluh,2023-12-27 12:57:28+00:00,Estoy intentando ser productiva pero mi cuerpo...,3,5,0,443
2,Joey Bamanas,@RedRyder1000rr,2023-12-27 01:15:30+00:00,I am full fledged geeking the fuck out with th...,0,0,0,21
3,JoeyJoJo,@JoeyGcartoonist,2023-12-27 16:14:39+00:00,With a little help from my coworker \r\nWe ma...,0,0,0,0
4,Terry Sessor,@terrysessor5,2023-12-27 21:40:15+00:00,Just how I like my meat - 3D printed …\r\n\r\...,0,0,0,15
...,...,...,...,...,...,...,...,...
22477,8BitofFun-On Vacation,@8BitoffunX,2024-03-10 00:35:37+00:00,Slingshot almost done!!,0,0,0,0
22478,jimmie,@idonowatname,2024-03-10 10:03:04+00:00,Anyone good with CAD help me modelll i wanna ...,0,0,0,0
22479,3D Printing @𝟑𝐃𝐚𝐛𝐥𝐞,@3Dable,2024-03-10 14:57:47+00:00,http:// #3Dprinting »Stratasys expands its so...,0,0,0,48
22480,Orland Park Library,@OrlandPkLibrary,2024-03-10 15:07:00+00:00,This class is a lecture overview on everything...,0,0,0,0
22481,M,@mooispulletjes,2024-03-11 04:49:39+00:00,3d printer te koop......,0,0,1,7

### Review Duplicate Tweets

In [ ]:
duplicates = df[df.duplicated(subset=['Date', 'Author ID'], keep=False)]

print("Duplicates based on 'Date' and 'Author ID':")
duplicates

duplicate_count = duplicates.shape[0]
print(f"Number of duplicate rows: {duplicate_count}")

Duplicates based on 'Date' and 'Author ID':
Number of duplicate rows: 411

### Review Tweet By Latest and Earliest

In [3]:
sorted_df = df.sort_values(by='Date', ascending=True)
sorted_df

,Author Name,Author ID,Date,Post Text,Replies,Likes,Reshares,Views
2617,Thor Odinson,@Thor_Odinson,2023-12-07 23:24:34+00:00,If someone builds up imaginary obstacles like ...,0,0,0,0
2620,MULMET,@MulmetCo_ltd,2023-12-07 23:29:21+00:00,Researchers have successfully demonstrated a p...,0,0,0,0
2606,reverb on master killguap industries ceo,@killguap,2023-12-07 23:30:49+00:00,bro tryna take off the temu switch from my 3d...,0,3,0,334
2632,y!!@Probably RnS. Forever.,@Shrimpy_shift11,2023-12-07 23:37:23+00:00,Seeing people mad that Metallic Rouge doesn't ...,0,0,0,93
2711,The 3D Print General,@3DPrintGeneral,2023-12-07 23:44:42+00:00,Front row for @TheAKGuy,11,641,32,16387
...,...,...,...,...,...,...,...,...
18521,Tala Rue,@Tala_Rue,2024-03-30 23:33:45+00:00,I would like very much for my 3D printer to ...,0,3,0,46
18581,SZ @ X3EM x/acc Ai Robotics 3D print skyscrapers,@3DX3EM,2024-03-30 23:34:05+00:00,Gravitational Waves is all you need! To create...,0,0,0,0
18578,Nelson De lanoi,@NLanoi86709,2024-03-30 23:34:07+00:00,Red Plume Men's Pullover Hoodie Sweatshirt 3D...,0,0,0,11
18835,Spacegamer64,@Spacegamer64,2024-03-30 23:37:46+00:00,Currently on EBay you can pickup a 3d printed...,0,0,0,0
18753,3D Print Master LLC,@3DPrintMasterCo,2024-03-30 23:47:28+00:00,With the help from TrueFab on Etsy we were ab...,0,8,1,303

In [4]:
earliest_date = df['Date'].min()
latest_date = df['Date'].max()

print(f"Earliest Date: {earliest_date}")
print(f"Latest Date: {latest_date}")

Earliest Date: 2023-12-07 23:24:34+00:00
Latest Date: 2024-03-30 23:47:28+00:00

## Create Global Record of Unique Tweets

In [ ]:

df['Date_str'] = df['Date'].dt.strftime('%Y-%m-%dT%H:%M:%S.%f').str[:-3] + 'Z'

df['tweet_unique_key'] = df['Date_str'] + '_' + df['Author ID']

deduplicated_df = df.drop_duplicates(subset=['tweet_unique_key'])

deduplicated_df.reset_index(drop=True, inplace=True)
deduplicated_df['Index'] = deduplicated_df.index + 1

deduplicated_df.sort_values(by='Date', inplace=True)

detailed_filename = "unique_tweet_records.csv"
deduplicated_df[['Index', 'Date', 'tweet_unique_key']].to_csv(detailed_filename, index=False)

minimal_filename = "unique_keys.csv"
deduplicated_df[['tweet_unique_key']].to_csv(minimal_filename, header=['tweet_unique_key'], index=False)

print(f"Detailed file saved as: {detailed_filename}")
print(f"Minimal file saved as: {minimal_filename}")

/tmp/ipykernel_3146/559969263.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  deduplicated_df['Index'] = deduplicated_df.index + 1
/tmp/ipykernel_3146/559969263.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  deduplicated_df.sort_values(by='Date', inplace=True)

Detailed file saved as: unique_tweet_records.csv
Minimal file saved as: unique_keys.csv

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17852 entries, 0 to 17851
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Author Name       17821 non-null  object
 1   Author ID         17852 non-null  object
 2   Date              17852 non-null  datetime64[ns, UTC]
 3   Post Text         17840 non-null  object
 4   Replies           17852 non-null  int64
 5   Likes             17852 non-null  int64
 6   Reshares          17852 non-null  int64
 7   Views             17852 non-null  int64
 8   Date_str          17852 non-null  object
 9   tweet_unique_key  17852 non-null  object
dtypes: datetime64[ns, UTC](1), int64(4), object(5)
memory usage: 1.4+ MB

In [21]:
deduplicated_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 17650 entries, 2417 to 13921
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Author Name       17619 non-null  object
 1   Author ID         17650 non-null  object
 2   Date              17650 non-null  datetime64[ns, UTC]
 3   Post Text         17638 non-null  object
 4   Replies           17650 non-null  int64
 5   Likes             17650 non-null  int64
 6   Reshares          17650 non-null  int64
 7   Views             17650 non-null  int64
 8   Date_str          17650 non-null  object
 9   tweet_unique_key  17650 non-null  object
 10  Index             17650 non-null  int64
dtypes: datetime64[ns, UTC](1), int64(5), object(5)
memory usage: 1.6+ MB

In [22]:
deduplicated_df

,Author Name,Author ID,Date,Post Text,Replies,Likes,Reshares,Views,Date_str,tweet_unique_key,Index
2417,patesalo,@patesalo_e,2023-12-18 12:49:05+00:00,PyroGenesis Receives New U.S. Patent for Its I...,0,0,0,25,2023-12-18 12:49:05+00:00,2023-12-18 12:49:05+00:00_@patesalo_e,2418
2427,Antoine Algian,@Antoine_Algian,2023-12-18 12:50:17+00:00,What a day to be a @BoDoggosNFT holder! Wel...,0,0,0,0,2023-12-18 12:50:17+00:00,2023-12-18 12:50:17+00:00_@Antoine_Algian,2428
2384,Bunny Lovers,@bunnylovers0,2023-12-18 12:51:09+00:00,New Released!!! Rabbit 3D Print T-shirt!! ...,0,0,0,0,2023-12-18 12:51:09+00:00,2023-12-18 12:51:09+00:00_@bunnylovers0,2385
2414,USA Rabbit Lovers,@usarabbitlovers,2023-12-18 12:51:48+00:00,New Released!!! Rabbit 3D Print T-shirt!! ...,0,0,0,0,2023-12-18 12:51:48+00:00,2023-12-18 12:51:48+00:00_@usarabbitlovers,2415
2483,Moritz Rudek / Reast,@ReastArtZ,2023-12-18 12:51:48+00:00,"As part of my university assignment, I had to ...",0,5,0,307,2023-12-18 12:51:48+00:00,2023-12-18 12:51:48+00:00_@ReastArtZ,2484
...,...,...,...,...,...,...,...,...,...,...,...
13689,Tala Rue,@Tala_Rue,2024-03-30 23:33:45+00:00,I would like very much for my 3D printer to ...,0,3,0,46,2024-03-30 23:33:45+00:00,2024-03-30 23:33:45+00:00_@Tala_Rue,13690
13749,SZ @ X3EM x/acc Ai Robotics 3D print skyscrapers,@3DX3EM,2024-03-30 23:34:05+00:00,Gravitational Waves is all you need! To create...,0,0,0,0,2024-03-30 23:34:05+00:00,2024-03-30 23:34:05+00:00_@3DX3EM,13750
13746,Nelson De lanoi,@NLanoi86709,2024-03-30 23:34:07+00:00,Red Plume Men's Pullover Hoodie Sweatshirt 3D...,0,0,0,11,2024-03-30 23:34:07+00:00,2024-03-30 23:34:07+00:00_@NLanoi86709,13747
14003,Spacegamer64,@Spacegamer64,2024-03-30 23:37:46+00:00,Currently on EBay you can pickup a 3d printed...,0,0,0,0,2024-03-30 23:37:46+00:00,2024-03-30 23:37:46+00:00_@Spacegamer64,14004
13921,3D Print Master LLC,@3DPrintMasterCo,2024-03-30 23:47:28+00:00,With the help from TrueFab on Etsy we were ab...,0,8,1,303,2024-03-30 23:47:28+00:00,2024-03-30 23:47:28+00:00_@3DPrintMasterCo,13922